### ISSUE TITLE
Used skill points show incorrect calculation when non-class skills have allocations

### ISSUE THREAD

**Issue by agrtga** [Rughalt/D35E#195]
The Used value for skill points is incorrect when non-class skills have points allocated. The total seems to reflect the total number of ranks in use not the skill points used.

**Comment by Rughalt** [comment]
These values will be hidden for characters using class progression. Keeping them correct in this case would be very hard and time consuming. These boxes will be shown - and intact -only when *not* using class progressions since they are approximate skill point values *and* applying skill points correctly in case of multiclass NPCs will always be wrong without using class progression either way. Monsters from different sources - and even NPCs with classes - seem to have arbitrary skill values in many instances.
