### ISSUE TITLE
Make the Grapple roll complete

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#236]
The Grapple roll as it stands just rolls the opposed strength check component.

It would be good if rolling Grapple in the sheet and the TAH does the touch attack component as well

So it would be 
Melee touch attack
Grapple Check
Damage as unarmed strike

GRAPPLE (PHB 155) Standard
• To start: make a melee touch attack to grab opponent, provokes AoO from
target; if AoO does damage, you fail to grapple.
• If attack succeeds, attacker and opponent make opposed grapple checks to
start the grapple.
▪ Grapple check = base attack + STR mod + special size mod.
▪ Special size mod: Colossal +16, Gargantuan +12, Huge +8, Large +4,
Small -4, Tiny -8, Diminutive -12, Fine -16.
• If succeeds, damage as unarmed strike. To maintain, move into target’s space
(provokes AoO from others).
• Can join a grapple: no AoO from target, grab succeeds automatically
• When grappled: cannot threaten, no DEX bonus, cannot move.
• Make opposed grapple check to do any of following:
▪ 1d3 + STR mod nonlethal damage (-4 to check for normal damage).
▪ Pin target, or break the pin a target has over an ally.
▪ Escape the Grapple.
▪ Draw light weapon.
▪ Use opponents weapon (-4 ATK).
▪ Move ½ speed (everyone in the grapple moves).
• Can attack with light weapons (only) when grappled.
• Escape artist check vs. grapple check to wriggle free as a standard action and
move away.

**Comment by Straddlecat** [comment]
https://www.dandwiki.com/wiki/SRD:Grapple

**Comment by Rughalt** [comment]
Moved to 0.89 as this will not only implement full grapple with counter roll, it will also implement trip and bull rush

**Comment by Rughalt** [comment]
Because of different ways grapple can start, implementation will *not* roll attack (since some monsters auto start grapple. Grapple rolls will however be modified. It would work like that:
- You roll unarmed attack/melee attack (for monsters with improved grab), selecting modifiers (manual action on your part)
- You roll grappled check, selecting modifiers
- Enemy rolls grapple check using button on your grapple check, selecting modifiers (he can also roll it using TAH, but there will be no auto resolution). That roll checks if grapple succeeded. If yes, you apply the damage from attack roll (manually), and you can apply "grappled" state to both actors.

**Comment by Rughalt** [comment]
Added, will be out in 0.89
- Added combat changes for grapple
- Added versus roll
![image](https://user-images.githubusercontent.com/802214/107943325-d97ec300-6f8c-11eb-9b72-edf4367a1f24.png)
