### ISSUE TITLE
Enhancement bonus not being applied to touch AC for NPC character sheets

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#245]
0.87.15

![image](https://user-images.githubusercontent.com/22633854/104037190-43f15600-51cc-11eb-9b73-e5bc850431a7.png)

[fvtt-Actor-Rogue.zip](https://github.com/Rughalt/D35E/files/5788189/fvtt-Actor-Rogue.zip)

**Comment by Rughalt** [comment]
This is because two things:
1. There was en error in the system that applied enhancement (from item sheet, not enhancement tab) bonus to AC always as armor enhancement bonus (this should work like that *but only for armor and shield*) - this is fixed, and will be out in 0.88
2. Ring of Protection gives Deflection AC type - there is special enhancement for those in the Enhancement compendium. Deflection also adds Touch AC
