### ISSUE TITLE
Wildcard Tokens

### ISSUE THREAD

**Issue by Cosmic-Lattee** [Rughalt/D35E#350]
So there is something going wrong with Wildcard Token images, I think it has to do with the little box in the character sheet not liking them. They do "work" but throw up a error each time you place one: 

![image](https://user-images.githubusercontent.com/24766235/107892436-b0a5f180-6eea-11eb-9adc-6680c58ca745.png)

**Comment by Rughalt** [comment]
I've looked how wildcard tokens work and they are incompatible with token override from actor sheet and I do not see easy way to make them compatible (foundry *replaces* wildcard when dropping actor on map, instead of keeping `*` in path). Solution set "Do not Override Token Image" to true and set up wildcard token directly in token settings.
![image](https://user-images.githubusercontent.com/802214/109384064-b1775400-78ea-11eb-87a3-62eaedf1dc9a.png)
