### ISSUE TITLE
[Bug] Spell Focus Feat making chosen schools spells not work.

### ISSUE THREAD

**Issue by Gritakthegoblin** [Rughalt/D35E#407]
Hello, I'm Goblin. I am encountering a bug with the Spell Focus feat. All the spells from the chosen school will not activate or even use up the prepared slot of the spell once used.

Unfortunately I don't have much else to report about this issue.

**Comment by Cosmic-Lattee** [comment]
I am having the same issue. Here is what is happening on my end:

![image](https://user-images.githubusercontent.com/24766235/110270845-5ef20380-7f8c-11eb-96a8-cd0586e7df11.png)

So that is set up then you try to cast the spell you get this far:

![image](https://user-images.githubusercontent.com/24766235/110270878-6f09e300-7f8c-11eb-8905-11273cb551b2.png)

Then nothing happens. Here is what the F12 log says:

![image](https://user-images.githubusercontent.com/24766235/110270926-8943c100-7f8c-11eb-99de-c28cca621514.png)

**Comment by Rughalt** [comment]
This warrants a hotfix I think, thanks!

**Comment by Rughalt** [comment]
Will be out in 0.90.2
