### ISSUE TITLE
Barbare enraged wrong time calculation

### ISSUE THREAD

**Issue by Dany-Deaneris** [Rughalt/D35E#776]
![image](https://user-images.githubusercontent.com/74456344/133871128-d7174cd4-1680-4897-a248-ea36fc5f855a.png)

As seen in this image the math at the end should be removed because the duration is only 3+ Constitution modifier.

**Comment by Rughalt** [comment]
This is problematic because of how it is all applied (it has to take into account *new* constitution modifier, not old one). If the buff does not exist, this calculation is incorrect, but if it is already there, it will be calculated correctly. However, as the buff is removed after it expired, I will make it so its correct when creating, not when applying the second time.
