### ISSUE TITLE
Apply Half Damage Doesn't Work

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#871]
![image](https://user-images.githubusercontent.com/22633854/146829467-f57342dd-dabc-4066-a004-25861dc3a447.png)
![image](https://user-images.githubusercontent.com/22633854/146829509-9f5d9392-3c38-4e8c-b3b2-c22e6f1f791f.png)

**Comment by PaulGRump** [comment]
I saw this and wanted to add some information from my own experience (same version): Applying half damage *does* work, for me anyway, but only when using damage types the system recognizes. This includes a new damage type I have since then added myself, but not when I simply write an unknown string in the field for custom damage types. My best guess is that the calculation runs into issues trying to check for damage reduction / resistance for damage types that don't exist, but I haven't looked any further into it.

Are you using a custom damage type in the screenshot you posted? Does the issue persist if you use a default damage type? Or maybe it even has something to do with energy damage vs. basic damage; I don't know. Just hope this information helps to track down the issue and/or find a workaround till then.

**Comment by Straddlecat** [comment]
No this was just vanilla weapon damage

**Comment by Straddlecat** [comment]
![image](https://user-images.githubusercontent.com/22633854/146967247-11b34490-5859-4b8a-8274-f2e4e5fcd8c4.png)

**Comment by PaulGRump** [comment]
Well, never mind then. I'll keep an eye on my issue and report back if I should find something relevant. 
I did notice that default weapon attacks seem to list their damage type as custom for some reason rather than having it selected in the drop-down, but I haven't yet investigated whether that has any impact either way.
